version: "3.8"
services:
  app:
    build:
      context: ./docker
    image: php-got-api
    container_name: got-api-app
    ports: 
      - "8080:80"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  db:
    image: mysql
    container_name: got-api-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - default